### PR TITLE
add url suffix

### PR DESCRIPTION
**Pull request by cognosticator**
Those of us in different azure domains (e.g. ".us") need to specify the last part of the azure endpoint. You may want to just add it to AzureAnalytics. I included the changes to AzureLogAnalytics for completeness.

### CODE REVIEW

**Comment by saleem-mirza** [comment]
Looks great. Thank you for your contribution. I'm looking forward more to come :)

**Comment by saleem-mirza** [comment]
@cognosticator I have converted TLD suffix to Enum type. This will limit user from entering invalid data. Now it offers two possible values. AzureOfferingType.US_Govenment and AzureOfferingType.Public

**Comment by cognosticator** [comment]
Okay. Little typo - it should be AzureOfferingType.US_Government. I look forward to using the official release!


Thanks!


Christopher Powell

Developer
3110 Fairview Park Drive, Suite 800 | Falls Church, VA 22042
(m) 720.363.5786

christopher.powell@cognosante.com

[1507909626895_logo-small.png]


________________________________

**Comment by saleem-mirza** [comment]
@cognosticator, fix spelling issues. Thanks for sharp eye 👍

**Pull request merged**
