### PR TITLE
Add configuration option to include message template in log message.

### PR DESCRIPTION
**Pull request by nizmow**

### CODE REVIEW

**Comment by nizmow** [comment]
Implements #37

**Comment by simonpinn** [comment]
+1 without the message template it removes alot of the benefits of structured logging, please merge

**Comment by simonpinn** [comment]
Having branched and given this a go, it should just be ```eventObject.Add("MessageTemplate", logEvent.MessageTemplate?.Text);``` Rather than ```eventObject.Add("MessageTemplate", logEvent.MessageTemplate);``` otherwise the rendered message is appearing in Analytics as the MessageTemplate

**Comment by nizmow** [comment]
@simonpinn thanks for the feedback, I was away on medical leave for a while but I notice now that some changes have been committed to the main code that now add the message template, so I'll close this PR!

**Comment by PaddySe** [comment]
What happened with this? I can't find any way of enabling the inclusion of the MessageTemplate field, and it's not included in what's sent to Azure.

**Pull request closed without merging**
